export const userData = [
  {
    customerName: "Jane Cooper",
    company: "Microsoft",
    phoneNumber: "(225) 555-0118",
    email: "jane@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1662739200,
  },
  {
    customerName: "John Doe",
    company: "Apple",
    phoneNumber: "(123) 456-7890",
    email: "john@apple.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674048000,
  },
  {
    customerName: "Alice Smith",
    company: "Google",
    phoneNumber: "(987) 654-3210",
    email: "alice@google.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674056700,
  },
  {
    customerName: "Robert Johnson",
    company: "Amazon",
    phoneNumber: "(555) 123-4567",
    email: "robert@amazon.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674063300,
  },
  {
    customerName: "Emily Davis",
    company: "Facebook",
    phoneNumber: "(111) 222-3333",
    email: "emily@facebook.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674066000,
  },
  {
    customerName: "Michael Brown",
    company: "Microsoft",
    phoneNumber: "(444) 555-6666",
    email: "michael@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1662730800,
  },
  {
    customerName: "Sarah Johnson",
    company: "Amazon",
    phoneNumber: "(222) 333-4444",
    email: "sarah@amazon.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674079200,
  },
  {
    customerName: "David Wilson",
    company: "Apple",
    phoneNumber: "(555) 666-7777",
    email: "david@apple.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674084600,
  },
  {
    customerName: "Olivia Smith",
    company: "Google",
    phoneNumber: "(777) 888-9999",
    email: "olivia@google.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674095400,
  },
  {
    customerName: "Ethan Davis",
    company: "Microsoft",
    phoneNumber: "(111) 222-3333",
    email: "ethan@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674102600,
  },
  {
    customerName: "Emma Thompson",
    company: "Facebook",
    phoneNumber: "(444) 555-6666",
    email: "emma@facebook.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674106800,
  },
  {
    customerName: "Jacob Anderson",
    company: "Apple",
    phoneNumber: "(888) 999-0000",
    email: "jacob@apple.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674114000,
  },
  {
    customerName: "Sophia Martinez",
    company: "Google",
    phoneNumber: "(333) 444-5555",
    email: "sophia@google.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674117600,
  },
  {
    customerName: "Liam Adams",
    company: "Microsoft",
    phoneNumber: "(666) 777-8888",
    email: "liam@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674124200,
  },
  {
    customerName: "Ava Mitchell",
    company: "Amazon",
    phoneNumber: "(111) 222-3333",
    email: "ava@amazon.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674127800,
  },
  {
    customerName: "Noah Lee",
    company: "Facebook",
    phoneNumber: "(444) 555-6666",
    email: "noah@facebook.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674135000,
  },
  {
    customerName: "Isabella Wilson",
    company: "Microsoft",
    phoneNumber: "(888) 999-0000",
    email: "isabella@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674136800,
  },
  {
    customerName: "Mason Thompson",
    company: "Google",
    phoneNumber: "(333) 444-5555",
    email: "mason@google.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674140400,
  },
  {
    customerName: "Charlotte Garcia",
    company: "Apple",
    phoneNumber: "(666) 777-8888",
    email: "charlotte@apple.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674145800,
  },
  {
    customerName: "Elijah Davis",
    company: "Amazon",
    phoneNumber: "(111) 222-3333",
    email: "elijah@amazon.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674153000,
  },
  {
    customerName: "Amelia Rodriguez",
    company: "Facebook",
    phoneNumber: "(444) 555-6666",
    email: "amelia@facebook.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674154800,
  },
  {
    customerName: "James Perez",
    company: "Microsoft",
    phoneNumber: "(888) 999-0000",
    email: "james@microsoft.com",
    country: "United States",
    isActive: true,
    timeStamp: 1674167400,
  },
];
